export const GET_DOGS = 'GET_DOGS';
export const GET_DOG_NAME = 'GET_DOG_NAME';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_WEIGHT = 'ORDER_BY_WEIGHT';
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';
export const FILTER_BY_TEMPERAMENT = 'FILTER_BY_TEMPERAMENT';
export const FILTER_DOGS = 'FILTER_DOGS';
export const UPDATE_STATE_MODAL = 'UPDATE_STATE_MODAL'